//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Student
    {
        public int Sno { get; set; }
        public string Sname { get; set; }
        public string Ssex { get; set; }
        public Nullable<int> Sage { get; set; }
        public string Depart { get; set; }
    }
}
